### ISSUE TITLE
上传图片 保存后再次编辑，图片的样式有问题

### ISSUE THREAD

**Issue by shilijun** [knowledges/vue2.0-file-upload#3]
![issue](https://user-images.githubusercontent.com/2699625/58085144-bf188980-7bee-11e9-8765-45d54e8264e9.png)
上传图片 保存后再次编辑，图片的样式有问题，但是刷新后再次编辑 是可以的
![TIM截图20190521173533](https://user-images.githubusercontent.com/2699625/58085195-de171b80-7bee-11e9-87bd-e5dff60bec5a.png)

**Comment by knowledges** [comment]
这个不是主键本身的问题；

一般的我们打开网页时出现502 bad gateway
说明服务器没有相应，也就是我们的web服务器没有接到有效的信息导致的。
